{% extends 'lab/index.html.j2' %}
{% block title %}ru-it-audit-report{% endblock title %}
{% block header %}
<h1>ru-it-audit report</h1>
<p>Generated by ru-it-audit-notebook</p>
{% endblock header %}
